kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-user
rules:
  - apiGroups: ["*"]
    resources:
      - services
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources:
      - services/proxy
      - pods/proxy
      - pods/portforward
    verbs: ["get", "list", "watch", "create", "delete"]